version: "3"
services:
  node:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo/snappit
    ports:
      - 3000:3000

  mongo:
    image: mongo:3.4.21-xenial
